using System;
using System.IO;

namespace Doorstop
{
    public static class Loader
    {
        public static void Main(string[] args)
        {
            using (TextWriter tw = File.CreateText("doorstop_is_alive.txt"))
            {
                tw.WriteLine($"Hello! This text file was generated by Doorstop on {DateTime.Now:R}!");
                tw.WriteLine($"I was called with {args.Length} params!");

                for (int i = 0; i < args.Length; i++)
                    tw.WriteLine($"{i} => {args[i]}");

                tw.WriteLine($"Command line: {Environment.CommandLine}");

                tw.WriteLine();
                tw.WriteLine("Doorstop also set the following environment variables:");
                tw.WriteLine($"DOORSTOP_INVOKE_PATH = {Environment.GetEnvironmentVariable("DOORSTOP_INVOKE_DLL_PATH")}");
                tw.WriteLine($"DOORSTOP_MANAGED_FOLDER_DIR = {Environment.GetEnvironmentVariable("DOORSTOP_MANAGED_FOLDER_DIR")}");

                tw.WriteLine("Replace this DLL with a custom-made one to do whatever you want!");

                tw.Flush();
            }
        }
    }
}